name: echorift
version: '1.0'
main: kz.bejiihiu.echorift.Main
api-version: '1.21'
load: STARTUP
authors: [ bejiihiu.xs ]
folia-supported: true
description: "Echo Rift event plugin for Folia-only SMP."
commands:
  echorift:
    description: "Управление событиями EchoRift (op-only)."
    usage: "/echorift <start|stop|status|spawn|collapse|reload>"
